language: go
go:
  - 1.11.x
env:
  global:
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.11
    - IMAGE_NAME=flaviojmendes/weathergo
    - GO111MODULE=on
install: true
jobs:
  fast_finish: true
notifications:
  email:
    on_success: change
    on_failure: always